package clases;
// Generated 20-ene-2020 16:17:06 by Hibernate Tools 4.3.1.Final

/**
 * Class generated by hbm2java
 */
public class Class implements java.io.Serializable {

	private ClassId id;

	public Class() {
	}

	public Class(ClassId id) {
		this.id = id;
	}

	public ClassId getId() {
		return this.id;
	}

	public void setId(ClassId id) {
		this.id = id;
	}

}
