package clases;
// Generated 20-ene-2020 16:17:06 by Hibernate Tools 4.3.1.Final

/**
 * Weapon generated by hbm2java
 */
public class Weapon implements java.io.Serializable {

	private WeaponId id;

	public Weapon() {
	}

	public Weapon(WeaponId id) {
		this.id = id;
	}

	public WeaponId getId() {
		return this.id;
	}

	public void setId(WeaponId id) {
		this.id = id;
	}

}
